apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: frontend-clusters
  namespace: gitops-hybrid-demo
spec:
  clusterConditions:
   - type: OK
  clusterSelector:
    matchExpressions: []
    matchLabels:
      env: "dev"
      tier: "frontend"
  clusterReplicas: 1