apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
   name: backend-dev-clusters
   namespace: gitops-hybrid-demo
spec:
   clusterConditions:
      - type: OK
   clusterSelector:
      matchExpressions: []
      matchLabels:
         environment: "dev"
         tier: "backend"
