apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
   name: hybrid-demo-backend-subscription
   labels:
      cloud: Amazon
   annotations:
      apps.open-cluster-management.io/github-path: backend/overlays/aws
spec:
   placement:
      placementRef:
         kind: PlacementRule
         name: dev-clusters-backend-aws
