apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
   name: backend-subscription
   labels:
      cloud: Google
   annotations:
      apps.open-cluster-management.io/github-path: backend/overlays/gcp
spec:
   placement:
      placementRef:
         kind: PlacementRule
         name: dev-clusters-backend-gcp
