apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
   name: frontend-dev-cluster
spec:
   clusterConditions:
      - type: OK
   clusterSelector:
      matchExpressions: []
      matchLabels:
         environment: "dev"
   clusterReplicas: 1
