apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
   name: dev-clusters-backend
spec:
   clusterConditions:
      - type: OK
   clusterSelector:
      matchExpressions: []
      matchLabels:
         environment: "dev"
         tier: "backend"
