apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
   name: hybrid-cloud-gcp-backend
   namespace: gitops-hybrid-demo
spec:
   componentKinds:
      - group: apps.open-cluster-management.io
        kind: Subscription
   descriptor: {}
   selector:
      matchExpressions:
         - key: cloud
           operator: In
           values:
              - Google
